version: '3.8'
services:
  frontend:
    image: michaeleliyahu/job-platform-frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    image: michaeleliyahu/job-platform-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge