version: '3.8'
services:
  frontend:
    image: michaeleliyahu/job-platform-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: michaeleliyahu/job-platform-backend:latest
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
